site_name: Kickstart-Guide
docs_dir: docs
site_dir: site
site_url: https://infinitepain.github.io/Kickstart-Guide/
copyright: Copyright &copy; 2024 Ahmet Emirhan Göktaş
repo_name: InfinitePain/Kickstart-Guide
repo_url: https://github.com/InfinitePain/Kickstart-Guide
edit_uri: blob/main/docs/

plugins:
  - search
  - with-pdf:
      author: Ahmet Emirhan Göktaş
      copyright: Copyright &copy; 2024 Ahmet Emirhan Göktaş
      cover: true
      back_cover: true
      cover_title: Kickstart-Guide
      cover_subtitle: A quick reference guide for developers
      enabled_if_env: ENABLE_PDF_EXPORT
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - git-authors
  - literate-nav:
      nav_file: NAV.md
      tab_length: 2

theme:
  name: material
  custom_dir: mkdocs-config/overrides
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4

  features:
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
      linenums: false
      linenums_style: pymdownx-inline
      anchor_linenums: true
      auto_title: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - abbr
  - toc:
      permalink: true

extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: Deutsch
      link: ./de/
      lang: de
  version:
    provider: mike
    default:
      - main
      - dev
